---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_solo
  root_path: /home/vagrant/kitchen

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          filename: "riak_2.0.0beta1-1_amd64.deb"
          checksum: "fbbd08bcfcef012a7ed9ce6c4744862fdf4642ba7a8eeed7d00beb465466d863"
        enterprise:
          checksum: "a700c3284a687bb4a8298da99d6c1886ba41e931662bf10075566125544d162d"
- name: debian-7.2.0
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          filename: "riak_2.0.0beta1-1_amd64.deb"
          checksum: "076b7bd58f179bed13da8cbb9b6cdaba7b123da8ada14e80b84b4e214bf24781"
        enterprise:
          checksum: "554e48bc39424c3bf08b357add663ad86bcc618d63755a601efdc608aa016a79"
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.0beta1-1.el6.x86_64.rpm"
          checksum: "2789de9a0d5eb536acb6eb5766393239e824b59e7da9055a765dca3c0596e110"
        enterprise:
          checksum: "7fdd3bca7d4d8961a601dc70925398ddb31c0f56d8f823596e6920d27f26f5db"
- name: centos-5.10
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.0beta1-1.el5.x86_64.rpm"
          checksum: "156401435bd2d0e30d5eec0f39c4e12b29b0bc4d0dc0d9e3c6f3672bcf2956b6"
        enterprise:
          checksum: "77b1e6c05040f4d47051208a23d85234c4532875a3afdbe451c63e81d175c021"
- name: fedora-19
  attributes:
    riak:
      package:
        local:
          checksum: "49264c49e025100126e83530ea8e5b690812da200bc4d5030338229148a43f99"
        enterprise:
          checksum: "d4381b2e976459b7a5775e4e3e2189b1a75daaf2c8fd825631fb8551a1e9f9b8"

suites:
- name: default
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        local:
          filename: ""
        version:
          major: "2"
          minor: "0"
          incremental: "0beta1"
- name: enterprise
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        url: "http://private.downloads.basho.com/riak_ee"
        version:
          major: "2"
          minor: "0"
          incremental: "0beta1"
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
  excludes:
  - fedora-19
- name: custom_package
  run_list:
  - recipe[riak]
  attributes: {}
- name: custom_repository
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_repository"
- name: source
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "source"
      source:
        major: "2"
        minor: "0"
        incremental: "0beta1"
