---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "538aee5b5d1081465cc828482be70bae6e3d4e31f10321e7563fde62c902c1af"
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "538aee5b5d1081465cc828482be70bae6e3d4e31f10321e7563fde62c902c1af"
- name: debian-7.2.0
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          debian:
            "7": "2808a15b8b1b29e002e7aacc37c06dfaf42cb5ab1eebac3d0171c6f2c008466e"
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "9794847ed23efd20927d4b1ff61d0ca60a41ae359b4dbf8e2b89ef18933108d8"
- name: centos-5.10
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "5": "3ef25500b859e050d9d1f196f5a9fe271760d92bc66bcbad29138ccc7aaa6f74"

suites:
- name: default
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 12
- name: default13
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 3
          incremental: 2
- name: default12
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 2
          incremental: 1
- name: enterprise
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 12
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise13
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 3
          incremental: 3
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise12
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 2
          incremental: 1
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: custom_repository
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_repository"
- name: custom_repository_enterprise
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        name: "riak-ee"
      install_method: "custom_repository"
- name: source
  run_list:
  - recipe[riak::source]
  attributes: {}
- name: source13
  run_list:
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          major: 1
          minor: 3
          incremental: 2
- name: source12
  run_list:
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          major: 1
          minor: 2
          incremental: 1
